name: Auto check label

on:
  issues:
    types:
      - reopened
      - opened
      - labeled
      - unlabeled
      - closed
  pull_request:
    types:
      - reopened
      - opened
      - labeled
      - unlabeled

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GH_PAT: ${{ secrets.GITHUB_TOKEN }}
  EVENT: ${{ toJSON(github.event)}}
  EVENT_NAME: ${{ github.event_name}}

jobs:
  sync:
    name: auto check label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - uses: HarrisChu/auto_label@v1
