name: auto-add-label

on:
  schedule:
    - cron: '0 18 * * *'
  issues:
    types:
      - reopened
      - opened
      - labeled
      - unlabeled
  pull_request:
    types: 
      - reopened
      - opened
      - labeled
      - unlabeled

jobs:
  build:
    name: auto add label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: ./
        with:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
