name: auto-add-label

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:


jobs:
  sync:
    name: auto add label
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{ secrets.GITHUB_TOKEN }}
      ISSUE_LABEL: "type;priority"
      PR_LABEL: "type;priority;day"
      REPO_NAME: "qianbd/staffSystem"
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: qianbd/auto_label@feat-add-code
      - name: lll
        run: ls
      - name: Install requirements
        run: pip3 install -r /qianbd/auto_label/feat-add-code/auto_label/label/requirements.txt
      - name: add lebal
        run: python3 /qianbd/auto_label/feat-add-code/auto_label/label/auto_label.py
